### ISSUE TITLE
Ollama setup with latest litellm issue

### ISSUE THREAD

**Issue by kulbinderdio** [bionic-gpt/bionic-gpt#176]
Using the following ollama.yml setup file

```
services:

  llm-api:
    image: ghcr.io/berriai/litellm:main-v1.12.2
    command: --model ollama/llama2 --api_base http://host.docker.internal:11434 --host 0.0.0.0 --port 3000
    platform: linux/amd64
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

I get the errors below

```
bionic-llm-api-1         | Docs: https://docs.litellm.ai/docs/simple_proxy
bionic-llm-api-1         | 
bionic-llm-api-1         | An exception occurred - Traceback (most recent call last):
bionic-llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 240, in user_api_key_auth
bionic-llm-api-1         |     api_key = _get_bearer_token(api_key=api_key)
bionic-llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 225, in _get_bearer_token
bionic-llm-api-1         |     assert api_key.startswith("Bearer ") # ensure Bearer token passed in
bionic-llm-api-1         | AssertionError
bionic-llm-api-1         | 
bionic-llm-api-1         | INFO:     172.26.0.9:33486 - "POST /v1/chat/completions HTTP/1.1" 401 Unauthorized
bionic-app-1             | 2023-12-11T17:29:42.331207Z  INFO axum_server::prompt: prompt.name="Default (Exclude All Datasets)"
bionic-app-1             | 2023-12-11T17:29:42.331217Z  INFO axum_server::prompt: Retrieved 0 chunks
bionic-app-1             | 2023-12-11T17:29:42.331425Z  INFO axum_server::prompt: Retrieved 0 history items
bionic-app-1             | 2023-12-11T17:29:42.331429Z  INFO axum_server::prompt: Using context size of 1024
bionic-llm-api-1         | An exception occurred - Traceback (most recent call last):
bionic-llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 240, in user_api_key_auth
bionic-llm-api-1         |     api_key = _get_bearer_token(api_key=api_key)
bionic-llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 225, in _get_bearer_token
bionic-llm-api-1         |     assert api_key.startswith("Bearer ") # ensure Bearer token passed in
bionic-llm-api-1         | AssertionError
bionic-llm-api-1         | 
bionic-llm-api-1         | INFO:     172.26.0.9:33502 - "POST /v1/chat/completions HTTP/1.1" 401 Unauthorized
bionic-app-1             | 2023-12-11T17:29:42.404333Z  INFO axum_server::prompt: prompt.name="Default (Exclude All Datasets)"
bionic-app-1             | 2023-12-11T17:29:42.404345Z  INFO axum_server::prompt: Retrieved 0 chunks
bionic-app-1             | 2023-12-11T17:29:42.404882Z  INFO axum_server::prompt: prompt.name="Default (Exclude All Datasets)"
bionic-app-1             | 2023-12-11T17:29:42.404889Z  INFO axum_server::prompt: Retrieved 0 chunks
bionic-app-1             | 2023-12-11T17:29:42.404916Z  INFO axum_server::prompt: Retrieved 0 history items
bionic-app-1             | 2023-12-11T17:29:42.404919Z  INFO axum_server::prompt: Using context size of 1024
bionic-app-1             | 2023-12-11T17:29:42.470315Z  INFO axum_server::prompt: Retrieved 0 history items
bionic-app-1             | 2023-12-11T17:29:42.470323Z  INFO axum_server::prompt: Using context size of 1024
bionic-llm-api-1         | An exception occurred - Traceback (most recent call last):
bionic-llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 240, in user_api_key_auth
bionic-llm-api-1         |     api_key = _get_bearer_token(api_key=api_key)
bionic-llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 225, in _get_bearer_token
bionic-llm-api-1         |     assert api_key.startswith("Bearer ") # ensure Bearer token passed in
bionic-llm-api-1         | AssertionError
bionic-llm-api-1         | 
bionic-llm-api-1         | INFO:     172.26.0.9:33510 - "POST /v1/chat/completions HTTP/1.1" 401 Unauthorized
bionic-llm-api-1         | An exception occurred - Traceback (most recent call last):
bionic-llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 240, in user_api_key_auth
bionic-llm-api-1         |     api_key = _get_bearer_token(api_key=api_key)
bionic-llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 225, in _get_bearer_token
bionic-llm-api-1         |     assert api_key.startswith("Bearer ") # ensure Bearer token passed in
bionic-llm-api-1         | AssertionError
bionic-llm-api-1         | 
bionic-llm-api-1         | INFO:     172.26.0.9:33512 - "POST /v1/chat/completions HTTP/1.1" 401 Unauthorized

```

having spoken to litellm guys, they say "an api key is being passed in Authorization header to the proxy, but it's not a bearer token"

Can we check what bionic is passing down
No key has been specified in front end so we shouldn't be passing anything down

**Comment by ianpurton** [comment]
@kulbinderdio I guess you're calling the Bionic API?

**Comment by ianpurton** [comment]
Fixed in latest version.
