### ISSUE TITLE
Errors in logs when starting with pgadmin container

### ISSUE THREAD

**Issue by kulbinderdio** [bionic-gpt/bionic-gpt#182]
The first time we start the pgadmin container, we have no issues. ON subsequent starts we have the following errors shown in the logs but pgadmin is still working

```
bionic-pgadmin-1         | 2023-12-13 13:59:56,568: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
bionic-pgadmin-1         | Traceback (most recent call last):
bionic-pgadmin-1         |   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
bionic-pgadmin-1         |     validate_csrf(self._get_csrf_token())
bionic-pgadmin-1         |   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
bionic-pgadmin-1         |     raise ValidationError("The CSRF session token is missing.")
bionic-pgadmin-1         | wtforms.validators.ValidationError: The CSRF session token is missing.
bionic-pgadmin-1         | 
bionic-pgadmin-1         | During handling of the above exception, another exception occurred:
bionic-pgadmin-1         | 
bionic-pgadmin-1         | Traceback (most recent call last):
bionic-pgadmin-1         |   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1482, in full_dispatch_request
bionic-pgadmin-1         |     rv = self.preprocess_request()
bionic-pgadmin-1         |          ^^^^^^^^^^^^^^^^^^^^^^^^^
bionic-pgadmin-1         |   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1974, in preprocess_request
bionic-pgadmin-1         |     rv = self.ensure_sync(before_func)()
bionic-pgadmin-1         |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bionic-pgadmin-1         |   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
bionic-pgadmin-1         |     self.protect()
bionic-pgadmin-1         |   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
bionic-pgadmin-1         |     self._error_response(e.args[0])
bionic-pgadmin-1         |   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
bionic-pgadmin-1         |     raise CSRFError(reason)
bionic-pgadmin-1         | flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
bionic-pgadmin-1         | 2023-12-13 13:59:56,569: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
bionic-pgadmin-1         | Traceback (most recent call last):
bionic-pgadmin-1         |   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
bionic-pgadmin-1         |     validate_csrf(self._get_csrf_token())
bionic-pgadmin-1         |   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
bionic-pgadmin-1         |     raise ValidationError("The CSRF session token is missing.")
bionic-pgadmin-1         | wtforms.validators.ValidationError: The CSRF session token is missing.
bionic-pgadmin-1         | 
bionic-pgadmin-1         | During handling of the above exception, another exception occurred:
bionic-pgadmin-1         | 
bionic-pgadmin-1         | Traceback (most recent call last):
bionic-pgadmin-1         |   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1482, in full_dispatch_request
bionic-pgadmin-1         |     rv = self.preprocess_request()
bionic-pgadmin-1         |          ^^^^^^^^^^^^^^^^^^^^^^^^^
bionic-pgadmin-1         |   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1974, in preprocess_request
bionic-pgadmin-1         |     rv = self.ensure_sync(before_func)()
bionic-pgadmin-1         |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bionic-pgadmin-1         |   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
bionic-pgadmin-1         |     self.protect()
bionic-pgadmin-1         |   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
bionic-pgadmin-1         |     self._error_response(e.args[0])
bionic-pgadmin-1         |   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
bionic-pgadmin-1         |     raise CSRFError(reason)
bionic-pgadmin-1         | flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
bionic-pgadmin-1         | ::ffff:172.26.0.1 - - [13/Dec/2023:13:59:56 +0000] "GET /dashboard/dashboard_stats/1/5?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:8888/browser/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0"
bionic-pgadmin-1         | ::ffff:172.26.0.1 - - [13/Dec/2023:13:59:56 +0000] "GET /dashboard/dashboard_stats/1/5?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:8888/browser/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0"
bionic-migrations-1 exited with code 0
bionic-app-1             | 2023-12-13T13:59:58.576323Z  INFO axum_server: listening on 0.0.0.0:7703
bionic-pgadmin-1         | 2023-12-13 14:00:01,277: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
bionic-pgadmin-1         | Traceback (most recent call last):
bionic-pgadmin-1         |   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
bionic-pgadmin-1         |     validate_csrf(self._get_csrf_token())
bionic-pgadmin-1         |   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
bionic-pgadmin-1         |     raise ValidationError("The CSRF session token is missing.")
bionic-pgadmin-1         | wtforms.validators.ValidationError: The CSRF session token is missing.
bionic-pgadmin-1         | 
bionic-pgadmin-1         | During handling of the above exception, another exception occurred:

```

**Comment by ianpurton** [comment]
Can you try this

```yml
services:

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
```

If that doesn't work figure it out yourself.
