### ISSUE TITLE
failed to lookup address information: Name does not resolve

### ISSUE THREAD

**Issue by plsnotracking** [bionic-gpt/bionic-gpt#354]
### Describe your issue

Device Details
```
OS: macOS 14.3 23D56 arm64
Host: MacBookPro18,2
CPU: Apple M1 Max
GPU: Apple M1 Max
Memory: 6869MiB / 65536MiB
```

Was trying to setup Bionic GPT on my local machine as mentioned in the [doc](https://bionic-gpt.com/docs/running-locally/apple-silicon/) here.

Running into 2 separate stack traces, not sure which is actually causing the issue:
**Stacktrace 1:**
```bash
unstructured-1    | Traceback (most recent call last):
unstructured-1    |   File "/home/notebook-user/.local/bin/uvicorn", line 8, in <module>
unstructured-1    |     sys.exit(main())
unstructured-1    |   File "/home/notebook-user/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
unstructured-1    |     return self.main(*args, **kwargs)
unstructured-1    |   File "/home/notebook-user/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
unstructured-1    |     rv = self.invoke(ctx)
unstructured-1    |   File "/home/notebook-user/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
unstructured-1    |     return ctx.invoke(self.callback, **ctx.params)
unstructured-1    |   File "/home/notebook-user/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
unstructured-1    |     return __callback(*args, **kwargs)
unstructured-1    |   File "/home/notebook-user/.local/lib/python3.10/site-packages/uvicorn/main.py", line 416, in main
unstructured-1    |     run(
unstructured-1    |   File "/home/notebook-user/.local/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
unstructured-1    |     server.run()
unstructured-1    |   File "/home/notebook-user/.local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
unstructured-1    |     return asyncio.run(self.serve(sockets=sockets))
unstructured-1    |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
unstructured-1    |     return loop.run_until_complete(main)
unstructured-1    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
unstructured-1    |     return future.result()
unstructured-1    |   File "/home/notebook-user/.local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
unstructured-1    |     config.load()
unstructured-1    |   File "/home/notebook-user/.local/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
unstructured-1    |     self.loaded_app = import_from_string(self.app)
unstructured-1    |   File "/home/notebook-user/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
unstructured-1    |     module = importlib.import_module(module_str)
unstructured-1    |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
unstructured-1    |     return _bootstrap._gcd_import(name[level:], package, level)
unstructured-1    |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
unstructured-1    |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
unstructured-1    |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
unstructured-1    |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
unstructured-1    |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
unstructured-1    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
unstructured-1    |   File "/home/notebook-user/prepline_general/api/app.py", line 6, in <module>
unstructured-1    |     from .general import router as general_router
unstructured-1    |   File "/home/notebook-user/prepline_general/api/general.py", line 43, in <module>
unstructured-1    |     from unstructured.partition.auto import partition
unstructured-1    |   File "/home/notebook-user/.local/lib/python3.10/site-packages/unstructured/partition/auto.py", line 81, in <module>
unstructured-1    |     from unstructured.partition.pdf import partition_pdf
unstructured-1    |   File "/home/notebook-user/.local/lib/python3.10/site-packages/unstructured/partition/pdf.py", line 81, in <module>
unstructured-1    |     from unstructured.partition.pdf_image.pdfminer_processing import (
unstructured-1    |   File "/home/notebook-user/.local/lib/python3.10/site-packages/unstructured/partition/pdf_image/pdfminer_processing.py", line 13, in <module>
unstructured-1    |     from unstructured_inference.models.detectron2onnx import UnstructuredDetectronONNXModel
unstructured-1    |   File "/home/notebook-user/.local/lib/python3.10/site-packages/unstructured_inference/models/detectron2onnx.py", line 6, in <module>
unstructured-1    |     import onnxruntime
unstructured-1    |   File "/home/notebook-user/.local/lib/python3.10/site-packages/onnxruntime/__init__.py", line 55, in <module>
unstructured-1    |     raise import_capi_exception
unstructured-1    |   File "/home/notebook-user/.local/lib/python3.10/site-packages/onnxruntime/__init__.py", line 23, in <module>
unstructured-1    |     from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
unstructured-1    |   File "/home/notebook-user/.local/lib/python3.10/site-packages/onnxruntime/capi/_pybind_state.py", line 33, in <module>
unstructured-1    |     from .onnxruntime_pybind11_state import *  # noqa
unstructured-1    | ImportError: /home/notebook-user/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so: cannot enable executable stack as shared object requires: Invalid argument
unstructured-1 exited with code 1
llm-api-1         | WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffffd191970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/async-generator/
```

**Stacktrace 2:**
```bash
app-1             | 2024-02-03T01:35:09.668735Z  INFO axum_server::prompt: prompt.name="Default (Exclude All Datasets)"
app-1             | 2024-02-03T01:35:09.669315Z  INFO axum_server::prompt: Retrieved 0 chunks
app-1             | 2024-02-03T01:35:09.671111Z  INFO axum_server::prompt: Retrieved 0 history items
app-1             | 2024-02-03T01:35:09.671483Z  INFO axum_server::prompt: Using context size of 1024
oauth2-proxy-1    | 192.168.65.1:28655 - bfa6432b-0906-49e3-9920-fc94d94b00df - bionicgpt.1fzq6@8alias.com [2024/02/03 01:35:09] localhost:7800 GET / "/static/spinner-yqCzwJ3-.svg" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" 200 428 0.047
app-1             | 2024-02-03T01:35:09.812960Z ERROR axum_server::errors: response="status = 422 Unprocessable Entity, message = error trying to connect: dns error: failed to lookup address information: Name does not resolve"
oauth2-proxy-1    | 192.168.65.1:28617 - 93446b1b-d4b9-4b24-aac5-b42495faee66 - bionicgpt.1fzq6@8alias.com [2024/02/03 01:35:09] localhost:7800 POST / "/completions/1" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" 200 140 0.160
oauth2-proxy-1    | 192.168.65.1:28655 - bc9b37f3-ccfa-48da-8958-42791c6711bd - bionicgpt.1fzq6@8alias.com [2024/02/03 01:35:09] localhost:7800 POST / "/app/team/1/update_response" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" 303 0 0.006
oauth2-proxy-1    | 192.168.65.1:28655 - 3788957a-6b8e-4194-a67a-4de8f9fd0115 - bionicgpt.1fzq6@8alias.com [2024/02/03 01:35:09] localhost:7800 GET / "/app/team/1/console/1" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" 200 9107 0.005
app-1             | 2024-02-03T01:35:09.851367Z  INFO axum_server::prompt: prompt.name="Default (Exclude All Datasets)"
app-1             | 2024-02-03T01:35:09.851399Z  INFO axum_server::prompt: Retrieved 0 chunks
app-1             | 2024-02-03T01:35:09.852048Z  INFO axum_server::prompt: Retrieved 0 history items
app-1             | 2024-02-03T01:35:09.852063Z  INFO axum_server::prompt: Using context size of 1024
oauth2-proxy-1    | 192.168.65.1:28654 - fbacb1cc-4192-4e97-8592-e73d77d07ad6 - bionicgpt.1fzq6@8alias.com [2024/02/03 01:35:09] localhost:7800 GET / "/static/handshake-73I4sNiD.svg" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" 200 2084 0.070
app-1             | 2024-02-03T01:35:09.927956Z ERROR axum_server::errors: response="status = 422 Unprocessable Entity, message = error trying to connect: dns error: failed to lookup address information: Name does not resolve"
oauth2-proxy-1    | 192.168.65.1:28655 - 146b36df-eaaf-470a-a75a-bcc9987217d8 - bionicgpt.1fzq6@8alias.com [2024/02/03 01:35:09] localhost:7800 POST / "/completions/1" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" 200 140 0.081
app-1             | 2024-02-03T01:35:09.999220Z  INFO axum_server::prompt: prompt.name="Default (Exclude All Datasets)"
app-1             | 2024-02-03T01:35:09.999241Z  INFO axum_server::prompt: Retrieved 0 chunks
app-1             | 2024-02-03T01:35:10.000493Z  INFO axum_server::prompt: Retrieved 0 history items
app-1             | 2024-02-03T01:35:10.000502Z  INFO axum_server::prompt: Using context size of 1024
app-1             | 2024-02-03T01:35:10.066316Z  INFO axum_server::prompt: prompt.name="Default (Exclude All Datasets)"
app-1             | 2024-02-03T01:35:10.066339Z  INFO axum_server::prompt: Retrieved 0 chunks
app-1             | 2024-02-03T01:35:10.067666Z  INFO axum_server::prompt: Retrieved 0 history items
app-1             | 2024-02-03T01:35:10.067677Z  INFO axum_server::prompt: Using context size of 1024
app-1             | 2024-02-03T01:35:10.140299Z ERROR axum_server::errors: response="status = 422 Unprocessable Entity, message = error trying to connect: dns error: failed to lookup address information: Name does not resolve"
oauth2-proxy-1    | 192.168.65.1:28617 - 54327a9c-6bf5-4ce4-98a7-f6898abe4ef1 - bionicgpt.1fzq6@8alias.com [2024/02/03 01:35:09] localhost:7800 POST / "/completions/1" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" 200 140 0.287
app-1             | 2024-02-03T01:35:10.166674Z ERROR axum_server::errors: response="status = 422 Unprocessable Entity, message = error trying to connect: dns error: failed to lookup address information: Name does not resolve"
oauth2-proxy-1    | 192.168.65.1:28656 - 8eb5b45a-4e8d-4ebe-9f6f-a63862aaafc4 - bionicgpt.1fzq6@8alias.com [2024/02/03 01:35:09] localhost:7800 POST / "/completions/1" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" 200 140 0.262
postgres-1        | 2024-02-03 01:37:07.143 UTC [301] LOG:  checkpoint starting: time
oauth2-proxy-1    | 192.168.65.1:28794 - 172ea559-6818-4adb-a6f3-ddf626414129 - bionicgpt.1fzq6@8alias.com [2024/02/03 01:38:39] localhost:7800 POST / "/app/team/1/send_message" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" 303 0 0.013
oauth2-proxy-1    | 192.168.65.1:28794 - 0a21ee9d-0f42-48f9-9943-7027e28c3757 - bionicgpt.1fzq6@8alias.com [2024/02/03 01:38:39] localhost:7800 GET / "/app/team/1/console/1" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" 200 10523 0.035
app-1             | 2024-02-03T01:38:39.914545Z  INFO axum_server::prompt: prompt.name="Default (Exclude All Datasets)"
app-1             | 2024-02-03T01:38:39.914601Z  INFO axum_server::prompt: Retrieved 0 chunks
app-1             | 2024-02-03T01:38:39.915432Z  INFO axum_server::prompt: Retrieved 0 history items
app-1             | 2024-02-03T01:38:39.915457Z  INFO axum_server::prompt: Using context size of 1024
app-1             | 2024-02-03T01:38:40.013971Z ERROR axum_server::errors: response="status = 422 Unprocessable Entity, message = error trying to connect: dns error: failed to lookup address information: Name does not resolve"
```

### Describe your setup/startup scripts

- `curl -O https://raw.githubusercontent.com/bionic-gpt/bionic-gpt/main/docker-compose/docker-compose.yml`
- `curl -O https://raw.githubusercontent.com/bionic-gpt/bionic-gpt/main/docker-compose/docker-compose-ollama.yml`
- `docker-compose -f docker-compose.yml -f docker-compose-ollama.yml up`
- Visit: `http://localhost:7800`

### Steps to reproduce

1. Visit: https://bionic-gpt.com/docs/running-locally/apple-silicon/
2. Follow the commands

<img width="749" alt="image" src="https://github.com/bionic-gpt/bionic-gpt/assets/54467867/a829f534-8b3e-4424-833b-c77b4d2152ab">

### What was the expected result?

Should run as expected.

### Any additional information

Tested the `llama2 model` as asked in the [doc](https://bionic-gpt.com/docs/running-locally/apple-silicon/)
That works fine. Snipped the O/P.
```bash
curl -X POST http://localhost:11434/api/generate -d '{
  "model": "llama2",
  "prompt":"Why is the sky blue?"
 }'

{"model":"llama2","created_at":"2024-02-03T01:51:15.930863Z","response":"\n","done":false}
.
.
.
{"model":"llama2","created_at":"2024-02-03T01:51:19.966899Z","response":"","done":true,"context":[518,25580,29962,3532,14816,29903,29958,5299,829,14816,29903,6778,13,13,11008,338,278,14744,7254,29973,518,29914,25580,29962,13,13,1576,14744,5692,7254,1363,310,263,27791,265,2000,9596,280,1141,14801,292,29892,607,10008,746,6575,4366,24395,11563,29915,29879,25005,29889,450,6575,4366,2094,1309,2153,21577,13206,21337,310,330,2129,1316,408,21767,307,1885,322,288,28596,29892,607,14801,278,3578,297,599,18112,29889,13,13,1576,3273,342,281,6447,1477,29879,310,3578,29892,1316,408,28008,1026,322,7254,29892,526,29574,901,1135,916,11955,29892,1316,408,2654,322,24841,29892,2861,304,1009,7968,281,6447,1477,29889,910,2794,393,1438,20511,281,6447,1477,29879,526,29106,287,10106,278,25005,29892,6820,278,14744,967,7254,10097,29889,13,13,2528,17658,29892,278,11563,29915,29879,25005,14741,763,263,544,1608,29892,2143,1461,292,313,272,289,2548,29897,278,3578,322,9677,292,372,714,29892,607,884,640,5026,304,278,7254,2927,310,278,14744,29889,450,5253,310,14801,292,322,2143,13857,508,13100,8679,373,278,931,310,2462,29892,278,14826,29892,322,278,10122,310,21180,329,1934,297,278,25005,29889,13,13,6295,29892,304,19138,675,29892,278,14744,5692,7254,1363,310,278,982,3578,16254,29879,411,278,21577,13206,21337,310,330,2129,297,11563,29915,29879,25005,29892,408,1532,408,278,982,278,25005,2143,1461,29879,322,885,271,2153,278,3578,29889],"total_duration":4636451667,"load_duration":512767834,"prompt_eval_count":26,"prompt_eval_duration":87387000,"eval_count":246,"eval_duration":4035971000}
```

**Comment by plsnotracking** [comment]
Filed a separate issue for unstructured: https://github.com/Unstructured-IO/unstructured/issues/2499

**Comment by plsnotracking** [comment]
Filed a separate issue for LiteLLM here: https://github.com/BerriAI/litellm/issues/1789

**Comment by 9876691** [comment]
A few changes have been made, can you chekcout the latest version?

**Comment by 9876691** [comment]
Closing, re-open if issue persists.
