### ISSUE TITLE
Inferencing from remote litellm-api Model results in "Error occurred while generating"

### ISSUE THREAD

**Issue by whalygood** [bionic-gpt/bionic-gpt#372]
### Describe your issue

Using a Docker Compose stack adapted from the CPU example in the docs, I am running an instance of Bionic-GPT.
I attempted to integrate an OpenAI compatible endpoint (by a managed provider) using the litellm container (as in the GPU example). 

![image](https://github.com/bionic-gpt/bionic-gpt/assets/31971061/270aa0ea-df20-4d16-a316-9df2c5674c03)

An excerpt from the error in the browser console is as follows:

```
data: {"id": "chatcmpl-48a30846-5f1e-491a-aa37-376f146a726e", "choices": [{"finish_reason": null, "index": 0, "delta": {"content": " you", "role": null}}], "created": 1707886719, "model": "mixtral-8x7b-instruct-fp16", "object": "chat.completion.chunk", "system_fingerprint": null, "
streaming-chat.ts:91  Error: SyntaxError: Unterminated string in JSON at position 276 (line 1 column 277)
    at JSON.parse (<anonymous>)
    at streaming-chat.ts:70:43
    at Array.forEach (<anonymous>)
    at r.streamResult (streaming-chat.ts:56:21)
```

### Describe your setup/startup scripts

The litellm-api container is running with the following stack definition on the same Docker network as the rest of Bionic-GPT.

```
 litellm-api:
    image: ghcr.io/berriai/litellm:main-v1.10.3
    platform: linux/amd64
    environment:
      OPENAI_API_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    command:
      - /bin/sh
      - -c
      - |
        pip install async_generator
        litellm --model openai/mixtral-8x7b-instruct-fp16 --api_base https://text.octoai.run/v1 --debug --host 0.0.0.0 --port 3000
    entrypoint: []
```

### Steps to reproduce

In **System Admin > Model Setup**, I added the model as follows:
mixtral-8x7b-instruct-fp16
http://litellm-api:3000/v1
7B Parameters
4096 Context Size

Then, I created a prompt which uses the above model.

Finally, I attempted to chat with the model in the Chat Console.

### What was the expected result?

Bionic-GPT makes the inference using the external model, and returns the AI generated text. 

### Any additional information

This is an excerpt from the the litellm-api container log:

```
litellm-api-1  | receiving data: {'model': 'mixtral-8x7b-instruct-fp16', 'stream': True, 'max_tokens': 1024, 'messages': [{'role': 'user', 'content': 'Hello'}], 'temperature': 0.7}
litellm-api-1  | litellm.cache: None
litellm-api-1  | kwargs[caching]: False; litellm.cache: None
litellm-api-1  | litellm.caching: False; litellm.caching_with_models: False; litellm.cache: None
litellm-api-1  | kwargs[caching]: False; litellm.cache: None
litellm-api-1  |
litellm-api-1  | LiteLLM completion() model= mixtral-8x7b-instruct-fp16; provider = openai
litellm-api-1  |
litellm-api-1  | LiteLLM: Params passed to completion() {'functions': [], 'function_call': '', 'temperature': 0.7, 'top_p': None, 'stream': True, 'max_tokens': 1024, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': '', 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': None, 'custom_llm_provider': 'openai', 'model': 'mixtral-8x7b-instruct-fp16', 'n': None, 'stop': None}
litellm-api-1  |
litellm-api-1  | LiteLLM: Non-Default params passed to completion() {'temperature': 0.7, 'stream': True, 'max_tokens': 1024}
litellm-api-1  | self.optional_params: {'temperature': 0.7, 'stream': True, 'max_tokens': 1024}
litellm-api-1  | PRE-API-CALL ADDITIONAL ARGS: {'headers': None, 'api_base': 'https://text.octoai.run/v1', 'acompletion': True, 'complete_input_dict': {'model': 'mixtral-8x7b-instruct-fp16', 'messages': [{'role': 'user', 'content': 'Hello'}], 'temperature': 0.7, 'stream': True, 'max_tokens': 1024}}
litellm-api-1  |
litellm-api-1  |
litellm-api-1  | POST Request Sent from LiteLLM:
litellm-api-1  | curl -X POST \
litellm-api-1  | https://text.octoai.run/v1 \
litellm-api-1  | -d '{'model': 'mixtral-8x7b-instruct-fp16', 'messages': [{'role': 'user', 'content': 'Hello'}], 'temperature': 0.7, 'stream': True, 'max_tokens': 1024}'
litellm-api-1  |
litellm-api-1  |
litellm-api-1  | RAW RESPONSE:
litellm-api-1  | <async_generator object OpenAIChatCompletion.async_streaming at 0x7f6e60703550>
litellm-api-1  |
litellm-api-1  |
litellm-api-1  | Logging Details Post-API Call: logger_fn - None | callable(logger_fn) - False
litellm-api-1  | Logging Details Post-API Call: LiteLLM Params: {'model': 'mixtral-8x7b-instruct-fp16', 'messages': [{'role': 'user', 'content': 'Hello'}], 'optional_params': {'temperature': 0.7, 'stream': True, 'max_tokens': 1024}, 'litellm_params': {'return_async': False, 'api_key': None, 'force_timeout': 600, 'logger_fn': None, 'verbose': False, 'custom_llm_provider': 'openai', 'api_base': 'https://text.octoai.run/v1', 'litellm_call_id': '51605bd0-e95a-493d-8c7f-b28dd731b86e', 'model_alias_map': {}, 'completion_call_id': None, 'metadata': {'user_api_key': None}, 'stream_response': {}}, 'start_time': datetime.datetime(2024, 2, 14, 4, 58, 5, 97485), 'stream': True, 'input': [{'role': 'user', 'content': 'Hello'}], 'api_key': 'REDACTED', 'additional_args': {'headers': None}, 'log_event_type': 'post_api_call', 'original_response': <async_generator object OpenAIChatCompletion.async_streaming at 0x7f6e60703550>}
litellm-api-1  | INFO:     172.18.0.9:55958 - "POST /v1/chat/completions HTTP/1.1" 200 OK
litellm-api-1  | inside generator
litellm-api-1  | RAW RESPONSE:
litellm-api-1  | <class 'openai.AsyncStream'>
litellm-api-1  |
litellm-api-1  |
litellm-api-1  | Logging Details Post-API Call: logger_fn - None | callable(logger_fn) - False
litellm-api-1  | Logging Details Post-API Call: LiteLLM Params: {'model': 'mixtral-8x7b-instruct-fp16', 'messages': [{'role': 'user', 'content': 'Hello'}], 'optional_params': {'temperature': 0.7, 'stream': True, 'max_tokens': 1024}, 'litellm_params': {'return_async': False, 'api_key': None, 'force_timeout': 600, 'logger_fn': None, 'verbose': False, 'custom_llm_provider': 'openai', 'api_base': 'https://text.octoai.run/v1', 'litellm_call_id': '51605bd0-e95a-493d-8c7f-b28dd731b86e', 'model_alias_map': {}, 'completion_call_id': None, 'metadata': {'user_api_key': None}, 'stream_response': {}}, 'start_time': datetime.datetime(2024, 2, 14, 4, 58, 5, 97485), 'stream': True, 'input': None, 'api_key': None, 'additional_args': {}, 'log_event_type': 'post_api_call', 'original_response': "<class 'openai.AsyncStream'>"}
litellm-api-1  |
litellm-api-1  | Raw OpenAI Chunk
litellm-api-1  | ChatCompletionChunk(id='cmpl-9c2d5db2b2014e838c748f7ca1dcb0b0', choices=[Choice(delta=ChoiceDelta(content=None, function_call=None, role='assistant', tool_calls=None), finish_reason=None, index=0)], created=1707886685, model='mixtral-8x7b-instruct-fp16', object=None, system_fingerprint=None)
litellm-api-1  |
litellm-api-1  | completion obj content:
litellm-api-1  | model_response: ModelResponse(id='chatcmpl-d7a8b829-36dd-4ddf-8dee-da81ba1b78d1', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=None, role=None))], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None, usage=Usage()); completion_obj: {'content': ''}
litellm-api-1  | model_response finish reason 3: None
litellm-api-1  |
litellm-api-1  | Raw OpenAI Chunk
litellm-api-1  | ChatCompletionChunk(id='cmpl-9c2d5db2b2014e838c748f7ca1dcb0b0', choices=[Choice(delta=ChoiceDelta(content=' Hello', function_call=None, role='assistant', tool_calls=None), finish_reason=None, index=0)], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None)
litellm-api-1  |
litellm-api-1  | completion obj content:  Hello
litellm-api-1  | model_response: ModelResponse(id='chatcmpl-e7417548-b821-4a1d-8782-87b7df4a45ae', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=None, role=None))], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None, usage=Usage()); completion_obj: {'content': ' Hello'}
litellm-api-1  | model_response finish reason 3: None
litellm-api-1  | hold - False, model_response_str - Hello
litellm-api-1  | Logging Details LiteLLM-Success Call
litellm-api-1  | success callbacks: []
litellm-api-1  | model_response: ModelResponse(id='chatcmpl-e7417548-b821-4a1d-8782-87b7df4a45ae', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='Hello', role='assistant'))], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None, usage=Usage())
litellm-api-1  | returned chunk: ModelResponse(id='chatcmpl-e7417548-b821-4a1d-8782-87b7df4a45ae', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='Hello', role='assistant'))], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None, usage=Usage())
litellm-api-1  |
litellm-api-1  | Raw OpenAI Chunk
litellm-api-1  | ChatCompletionChunk(id='cmpl-9c2d5db2b2014e838c748f7ca1dcb0b0', choices=[Choice(delta=ChoiceDelta(content='!', function_call=None, role='assistant', tool_calls=None), finish_reason=None, index=0)], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None)
litellm-api-1  |
litellm-api-1  | completion obj content: !
litellm-api-1  | model_response: ModelResponse(id='chatcmpl-0ea18a20-d763-41a6-9390-a67d056c95a9', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=None, role=None))], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None, usage=Usage()); completion_obj: {'content': '!'}
litellm-api-1  | model_response finish reason 3: None
litellm-api-1  | hold - False, model_response_str - !
litellm-api-1  | Logging Details LiteLLM-Success Call
litellm-api-1  | success callbacks: []
litellm-api-1  | model_response: ModelResponse(id='chatcmpl-0ea18a20-d763-41a6-9390-a67d056c95a9', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='!', role=None))], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None, usage=Usage())
litellm-api-1  | returned chunk: ModelResponse(id='chatcmpl-0ea18a20-d763-41a6-9390-a67d056c95a9', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='!', role=None))], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None, usage=Usage())
litellm-api-1  |
litellm-api-1  | Raw OpenAI Chunk
litellm-api-1  | ChatCompletionChunk(id='cmpl-9c2d5db2b2014e838c748f7ca1dcb0b0', choices=[Choice(delta=ChoiceDelta(content=' How', function_call=None, role='assistant', tool_calls=None), finish_reason=None, index=0)], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None)
litellm-api-1  |
litellm-api-1  | completion obj content:  How
litellm-api-1  | model_response: ModelResponse(id='chatcmpl-4b796b7e-78d4-49a7-955d-f4446ad33b33', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=None, role=None))], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None, usage=Usage()); completion_obj: {'content': ' How'}
litellm-api-1  | model_response finish reason 3: None
litellm-api-1  | hold - False, model_response_str -  How
litellm-api-1  | Logging Details LiteLLM-Success Call
litellm-api-1  | success callbacks: []
litellm-api-1  | model_response: ModelResponse(id='chatcmpl-4b796b7e-78d4-49a7-955d-f4446ad33b33', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' How', role=None))], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None, usage=Usage())
litellm-api-1  | returned chunk: ModelResponse(id='chatcmpl-4b796b7e-78d4-49a7-955d-f4446ad33b33', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' How', role=None))], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None, usage=Usage())
litellm-api-1  |
litellm-api-1  | Raw OpenAI Chunk
litellm-api-1  | ChatCompletionChunk(id='cmpl-9c2d5db2b2014e838c748f7ca1dcb0b0', choices=[Choice(delta=ChoiceDelta(content=' can', function_call=None, role='assistant', tool_calls=None), finish_reason=None, index=0)], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None)
litellm-api-1  |
litellm-api-1  | completion obj content:  can
litellm-api-1  | model_response: ModelResponse(id='chatcmpl-1b05088a-fb7f-4bcf-a0f0-058ad2524429', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=None, role=None))], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None, usage=Usage()); completion_obj: {'content': ' can'}
litellm-api-1  | model_response finish reason 3: None
litellm-api-1  | hold - False, model_response_str -  can
litellm-api-1  | Logging Details LiteLLM-Success Call
litellm-api-1  | success callbacks: []
litellm-api-1  | model_response: ModelResponse(id='chatcmpl-1b05088a-fb7f-4bcf-a0f0-058ad2524429', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' can', role=None))], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None, usage=Usage())
litellm-api-1  | returned chunk: ModelResponse(id='chatcmpl-1b05088a-fb7f-4bcf-a0f0-058ad2524429', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' can', role=None))], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None, usage=Usage())
litellm-api-1  |
litellm-api-1  | Raw OpenAI Chunk
litellm-api-1  | ChatCompletionChunk(id='cmpl-9c2d5db2b2014e838c748f7ca1dcb0b0', choices=[Choice(delta=ChoiceDelta(content=' I', function_call=None, role='assistant', tool_calls=None), finish_reason=None, index=0)], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None)
litellm-api-1  |
litellm-api-1  | completion obj content:  I
litellm-api-1  | model_response: ModelResponse(id='chatcmpl-4fba868b-55b9-4043-96ae-7154d1029bda', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=None, role=None))], created=1707886685, model='mixtral-8x7b-instruct-fp16', object='chat.completion.chunk', system_fingerprint=None, usage=Usage()); completion_obj: {'content': ' I'}
```

**Comment by swarris** [comment]
I'm seeing similar issues. I'm using the litellm docker to connect to a llama 13b local instance through the docker compose setup as described in the manual.

litellm communicates with the llama model:
```
INFO:     172.24.0.10:35164 - "POST /chat/completions HTTP/1.1" 200 OK
INFO:     172.24.0.10:35178 - "POST /chat/completions HTTP/1.1" 200 OK
```
And the model responses to this request:
```
[GIN] 2024/02/14 - 10:06:06 | 200 |   1.01154422s |      172.24.0.7 | POST     "/api/generate"
[GIN] 2024/02/14 - 10:06:06 | 200 |  202.834801ms |      172.24.0.7 | POST     "/api/generate"
[GIN] 2024/02/14 - 10:06:07 | 200 |   201.69017ms |      172.24.0.7 | POST     "/api/generate"
[GIN] 2024/02/14 - 10:06:07 | 200 |  182.670319ms |      172.24.0.7 | POST     "/api/generate"
```
The docker-compose logs also suggests everything is running smoothly:
```
llm-ollama-1      | INFO:     172.24.0.10:35154 - "POST /chat/completions HTTP/1.1" 200 OK
app-1             | 2024-02-14T10:06:06.761879Z  INFO axum_server::prompt: prompt.name="Ollama GPU"
app-1             | 2024-02-14T10:06:06.761913Z  INFO axum_server::prompt: Retrieved 0 chunks
app-1             | 2024-02-14T10:06:06.762436Z  INFO axum_server::prompt: Retrieved 0 history items
app-1             | 2024-02-14T10:06:06.762457Z  INFO axum_server::prompt: Using context size of 1638
```
However, in the browser (firefox on Ubuntu) I get this:
```
Error: SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 3 column 1 of the JSON data
    streamResult streaming-chat.ts:71
```
It seems getting a short reply does work. So just saying `hi` gives this reponse:
```
Hello! How can I assist you today? Please keep in mind that I'm just an AI and do not have access to personal information or the ability to perform physical actions. Is there something specific you would like to talk about or ask for help with?
```

**Comment by swarris** [comment]
For completeness: the ollama-2-7b defined in the main `docker-compose.yml` does work and returns a result, also with longer answers.

**Comment by swarris** [comment]
For me it was solved by using the most recent docker versions:
```
ghcr.io/bionic-gpt/bionicgpt-pipeline-job:1.5.32
ghcr.io/bionic-gpt/bionicgpt:1.5.32
```

**Comment by whalygood** [comment]
Tested with 1.5.32 and only first word of generative text is returned when using an external model through LiteLLM.

![image](https://github.com/bionic-gpt/bionic-gpt/assets/31971061/1d230ec0-c7d3-40de-af18-2671930edc30)

```
Uncaught (in promise) Error: missing finish_reason for choice 0
    at ChatCompletionStream.ts:262:35
    at Array.map (<anonymous>)
    at ChatCompletionStream.ts:260:22
    at tN.Y (ChatCompletionStream.ts:323:1)
    at tN._fromReadableStream (ChatCompletionStream.ts:132:49
```

**Comment by whalygood** [comment]
Upgrading the image version in the Compose file to the current version of LiteLLM appears to have resolved the issue.   

Old (not working): image: ghcr.io/berriai/litellm:main-v1.10.3
New: (working) image: ghcr.io/berriai/litellm:main-v1.23.16

So in conjunction with 1.5.32 of the BionicGPT container it looks like it's smooth sailing from here 🌊. 

![image](https://github.com/bionic-gpt/bionic-gpt/assets/31971061/52d08f03-82be-4b57-90f4-9b7a4424e059)
