### ISSUE TITLE
Chat returning errors

### ISSUE THREAD

**Issue by kulbinderdio** [bionic-gpt/bionic-gpt#98]
Installed latest containers on new linux (+Nvidia GPU) box.
Used the chat interface and was getting response

Uploaded attached document. It processed, but 3 parts errored.

I setup new prompt to query this document, but carried on getting errors
I removed the document and added a simple 1 line txt document but continued to get errors

I then used the default prompt and only got errors returned.
Couldn't see any errors output on the backend

[Gravesham Water and Flood Risk Background Paper.pdf](https://github.com/bionic-gpt/bionic-gpt/files/13326004/Gravesham.Water.and.Flood.Risk.Background.Paper.pdf)

**Comment by ianpurton** [comment]
Seems to somehow mess up the LLM.

```
{"timestamp":"2023-11-12T08:37:49.237378Z","level":"INFO","fields":{"message":"LLaMA - /app/model.bin - fully loaded in: 77ms !"},"target":"cria"}
{"timestamp":"2023-11-12T08:37:49.237468Z","level":"INFO","fields":{"message":"Running model inference thread !"},"target":"cria::inferer"}
{"timestamp":"2023-11-12T08:37:49.237503Z","level":"INFO","fields":{"message":"listening on 0.0.0.0:3000"},"target":"cria"}
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ContextFull', src/routes/chat.rs:127:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'Can't append the event on inference queue. Err "sending on a closed channel"', /usr/src/cria/src/inferer.rs:185:13
thread 'tokio-runtime-worker' panicked at 'Can't append the event on inference queue. Err "sending on a closed channel"', /usr/src/cria/src/inferer.rs:185:13
```

**Comment by ianpurton** [comment]
Context size was set incorrectly.
